---
- name: Atualizar o cache
  apt:
    update_cache: true

- name: Instalar os pacotes necessários para adicionar o repositório do Docker
  apt:
    name: "{{ repo_packages }}"
    state: latest

- name: Criar diretório para chave GPG do Docker
  file:
    path: /etc/apt/keyrings
    mode: 0755
    state: directory

- name: Adicionar a chave GPG do Docker
  shell:
    cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"

- name: Configurar o repositório do Docker
  shell:
    cmd: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'

- name: Garantir a permissão de leitura para a chave GPG do Docker
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: a+r

- name: Atualizar o cache
  apt:
    update_cache: true

- name: Instalar o Docker
  apt:
    name: "{{ docker_packages }}"
    state: latest

- name: Instalar o pip
  apt:
    name: python3-pip
    state: latest

- name: Instalar biblioteca Python do Docker
  pip:
    name: docker
    state: latest
...
